using System.Text;
using System.Xml.Linq;

namespace TALXIS.Platform.Metadata.Serialization.Xml.Scaffolding;

/// <summary>
/// Emits the &lt;UcfirstEntitySetName&gt;Model.ts TypeScript model from the model
/// solution's Entity.xml using LF line endings, no trailing newline and no BOM.
/// </summary>
internal static class CodeAppModelGenerator
{
    public static void Generate(string modelSolutionRootPath, string entityLogicalName, string outputPath)
    {
        var entityXmlPath = Path.Combine(modelSolutionRootPath, "Entities", entityLogicalName, "Entity.xml");
        if (!File.Exists(entityXmlPath))
            throw new FileNotFoundException($"Entity.xml not found at: {entityXmlPath}");

        var doc = XDocument.Load(entityXmlPath);
        var entityNode = doc.Root!.Element("EntityInfo")!.Element("entity")!;

        var entitySetName = entityNode.Element("EntitySetName")!.Value;
        var tsPrefix = char.ToUpper(entitySetName[0]) + entitySetName.Substring(1);

        var attributes = ParseAttributes(entityNode, modelSolutionRootPath);

        var sb = new StringBuilder();
        sb.AppendLine("/*!");
        sb.AppendLine(" * Copyright (C) Microsoft Corporation. All rights reserved.");
        sb.AppendLine(" * This file is autogenerated. Do not edit this file directly.");
        sb.AppendLine(" */");

        var optionSetAttrs = attributes
            .Where(a => (a.Type == "state" || a.Type == "status" || a.Type == "picklist") && a.Options != null && a.Options.Count > 0)
            .OrderBy(a => GetOptionSetOrder(a.Type))
            .ThenBy(a => a.LogicalName)
            .ToList();

        foreach (var attr in optionSetAttrs)
        {
            var typeName = tsPrefix + attr.LogicalName;
            sb.AppendLine($"export const {typeName} = {{");
            foreach (var kvp in attr.Options!.OrderBy(o => o.Key))
            {
                bool isLast = kvp.Key == attr.Options.OrderBy(o => o.Key).Last().Key;
                sb.AppendLine($"  {kvp.Key}: '{kvp.Value}'" + (isLast ? "" : ","));
            }
            sb.AppendLine("} as const;");
            sb.AppendLine($"export type {typeName} = keyof typeof {typeName};");
        }

        var baseFields = new List<BaseField>();
        foreach (var attr in attributes)
        {
            bool inBase = attr.ValidForCreateApi || attr.ValidForUpdateApi || attr.Type == "primarykey";
            if (!inBase) continue;

            bool isRequired = attr.RequiredLevel == "required" || attr.RequiredLevel == "systemrequired";
            string optional = isRequired ? "" : "?";

            if (attr.Type == "state" || attr.Type == "status" || attr.Type == "picklist")
            {
                baseFields.Add(new BaseField { Name = attr.LogicalName, TypeStr = tsPrefix + attr.LogicalName, Optional = optional });
            }
            else if (attr.Type == "lookup" && attr.IsCustomField)
            {
                baseFields.Add(new BaseField
                {
                    Name = $"\"{attr.LogicalName}@odata.bind\"",
                    SortKey = attr.LogicalName + "@odata.bind",
                    TypeStr = "string",
                    Optional = optional,
                });
            }
            else if (attr.Type == "lookup" && !attr.IsCustomField)
            {
                // Writable system lookups keep the _value-suffixed raw FK name so they
                // don't collide with the expanded object pair generated below.
                baseFields.Add(new BaseField { Name = $"_{attr.LogicalName}_value", TypeStr = "string", Optional = optional });
            }
            else if (attr.Type == "owner")
            {
                baseFields.Add(new BaseField { Name = attr.LogicalName, TypeStr = "string", Optional = optional });
                baseFields.Add(new BaseField { Name = attr.LogicalName + "type", TypeStr = "string", Optional = optional });
            }
            else
            {
                baseFields.Add(new BaseField { Name = attr.LogicalName, TypeStr = "string", Optional = optional });
            }
        }

        baseFields = baseFields.OrderBy(f => f.SortKey ?? f.Name).ToList();

        sb.AppendLine();
        sb.AppendLine($"export interface {tsPrefix}Base {{");
        foreach (var f in baseFields)
        {
            sb.AppendLine($"  {f.Name}{f.Optional}: {f.TypeStr};");
        }
        sb.AppendLine("}");

        sb.AppendLine();
        sb.AppendLine($"export interface {tsPrefix} extends {tsPrefix}Base {{");

        var stringProps = new List<ExtField>();
        var systemUserLookups = new HashSet<string> { "createdby", "createdonbehalfby", "modifiedby", "modifiedonbehalfby" };

        foreach (var attr in attributes)
        {
            if (attr.Type == "primarykey") continue;

            if ((attr.Type == "lookup" || attr.Type == "owner") && !attr.IsCustomField && !attr.IsLogical)
            {
                if (attr.Type == "owner" || attr.HasDisplayMask)
                {
                    bool nameRequired = attr.Type == "owner" || attr.LogicalName == "owningbusinessunit";
                    stringProps.Add(new ExtField { Name = attr.LogicalName + "name", TypeStr = "string", Optional = nameRequired ? "" : "?" });

                    if (systemUserLookups.Contains(attr.LogicalName) || attr.Type == "owner")
                    {
                        stringProps.Add(new ExtField { Name = attr.LogicalName + "yominame", TypeStr = "string", Optional = "" });
                    }
                }
            }

            if (attr.Type == "lookup" && attr.IsCustomField)
            {
                stringProps.Add(new ExtField { Name = attr.LogicalName + "name", TypeStr = "string", Optional = "?" });
            }

            if (attr.Type == "datetime" && !attr.ValidForCreateApi && !attr.ValidForUpdateApi)
            {
                stringProps.Add(new ExtField { Name = attr.LogicalName, TypeStr = "string", Optional = "?" });
            }

            if (attr.Type == "state" || attr.Type == "status" || attr.Type == "picklist")
            {
                stringProps.Add(new ExtField { Name = attr.LogicalName + "name", TypeStr = "string", Optional = "?" });
            }
        }

        stringProps.Add(new ExtField { Name = "versionnumber", TypeStr = "string", Optional = "?" });

        stringProps = stringProps.OrderBy(f => f.Name).ToList();
        foreach (var f in stringProps)
        {
            sb.AppendLine($"  {f.Name}{f.Optional}: {f.TypeStr};");
        }

        var lookupPairs = new List<string>();
        foreach (var attr in attributes)
        {
            if ((attr.Type == "lookup" || attr.Type == "owner") && !attr.IsCustomField && attr.Type != "owner")
                lookupPairs.Add(attr.LogicalName);
            if (attr.Type == "lookup" && attr.IsCustomField)
                lookupPairs.Add(attr.LogicalName);
        }

        lookupPairs = lookupPairs.OrderBy(n => n).ToList();
        foreach (var name in lookupPairs)
        {
            sb.AppendLine($"  {name}?: object;");
            sb.AppendLine($"  _{name}_value?: string;");
        }

        sb.AppendLine("}");

        Directory.CreateDirectory(outputPath);
        var outputFilePath = Path.Combine(outputPath, $"{tsPrefix}Model.ts");
        var result = sb.ToString().Replace("\r\n", "\n").TrimEnd('\n');
        File.WriteAllText(outputFilePath, result);
    }

    private static List<AttrInfo> ParseAttributes(XElement entityNode, string modelSolutionRootPath)
    {
        var attributes = new List<AttrInfo>();
        foreach (var attr in entityNode.Element("attributes")!.Elements("attribute"))
        {
            var info = new AttrInfo
            {
                LogicalName = attr.Element("LogicalName")?.Value ?? attr.Element("Name")?.Value ?? "",
                Type = attr.Element("Type")?.Value ?? "",
                RequiredLevel = attr.Element("RequiredLevel")?.Value ?? "none",
                ValidForCreateApi = attr.Element("ValidForCreateApi")?.Value == "1",
                ValidForUpdateApi = attr.Element("ValidForUpdateApi")?.Value == "1",
                IsCustomField = attr.Element("IsCustomField")?.Value == "1",
                IsLogical = attr.Element("IsLogical")?.Value == "1",
                HasDisplayMask = !string.IsNullOrEmpty(attr.Element("DisplayMask")?.Value),
            };

            var optionsetEl = attr.Element("optionset");
            if (optionsetEl != null)
            {
                info.Options = new Dictionary<int, string>();
                foreach (var state in optionsetEl.Descendants("state"))
                {
                    var val = int.Parse(state.Attribute("value")!.Value);
                    info.Options[val] = state.Descendants("label").FirstOrDefault()?.Attribute("description")?.Value ?? "";
                }
                foreach (var status in optionsetEl.Descendants("status"))
                {
                    var val = int.Parse(status.Attribute("value")!.Value);
                    info.Options[val] = status.Descendants("label").FirstOrDefault()?.Attribute("description")?.Value ?? "";
                }
                foreach (var opt in optionsetEl.Elements("options").Elements("option"))
                {
                    var val = int.Parse(opt.Attribute("value")!.Value);
                    info.Options[val] = opt.Descendants("label").FirstOrDefault()?.Attribute("description")?.Value ?? "";
                }
            }

            var optionSetNameEl = attr.Element("OptionSetName");
            if (optionSetNameEl != null && !string.IsNullOrEmpty(optionSetNameEl.Value))
            {
                var globalPath = Path.Combine(modelSolutionRootPath, "OptionSets", optionSetNameEl.Value + ".xml");
                if (File.Exists(globalPath))
                {
                    var globalDoc = XDocument.Load(globalPath);
                    info.Options = new Dictionary<int, string>();
                    foreach (var opt in globalDoc.Root!.Elements("options").Elements("option"))
                    {
                        var val = int.Parse(opt.Attribute("value")!.Value);
                        info.Options[val] = opt.Descendants("label").FirstOrDefault()?.Attribute("description")?.Value ?? "";
                    }
                }
            }

            attributes.Add(info);
        }
        return attributes;
    }

    private static int GetOptionSetOrder(string type) =>
        type switch { "state" => 0, "status" => 1, _ => 2 };

    private sealed class AttrInfo
    {
        public string LogicalName = "";
        public string Type = "";
        public string RequiredLevel = "none";
        public bool ValidForCreateApi;
        public bool ValidForUpdateApi;
        public bool IsCustomField;
        public bool IsLogical;
        public bool HasDisplayMask;
        public Dictionary<int, string>? Options;
    }

    private sealed class BaseField
    {
        public string Name = "";
        public string? SortKey;
        public string TypeStr = "";
        public string Optional = "";
    }

    private sealed class ExtField
    {
        public string Name = "";
        public string TypeStr = "";
        public string Optional = "";
    }
}
